### ISSUE TITLE
Переименовать константы и префиксы добавить

### ISSUE THREAD

**Issue by Otshelnik-Fm** [solidcreature/sample_tg_bot#3]
PLUGIN_DIR и PLUGIN_URL как имена для констант - не самая лучшая идея.

Вполне может оказаться подобная константа в других плагинах. Это принесет конфликт.

Лучше использовать префикс

my_awesome_func как имя функции - тоже не лучший вариант. 

p.s. - зачем использовать curl, когда в вордпресс есть бесконфликтный аналог? Например wp_remote_*

$row1 и т.д. зачем? Почему не $row[] = array(что-то...

**Comment by solidcreature** [comment]
Владимир, спасибо за содержательные замечания. Со всеми пунктами согласен, буду исправлять

**Comment by solidcreature** [comment]
Замену сurl на wp_remote_ пока не осилил. Постараюсь разобраться и учесть в следующих апдейтах. Названия констант и функций пофиксил. Еще раз спасибо
